{include file="section/head.phtml"}
{include file="css.phtml"}
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&language=fr" type="text/javascript"></script>
<title>Magix CMS | Admin</title>
</head>
<body class="plugins-contact">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="section/nav.phtml"}
                    <h1>Carte googlemap</h1>
                    <ul class="nav nav-tabs clearfix">
                        <li{if !$smarty.get.tab} class="active"{/if}>
                            <a href="/admin/plugins.php?name=gmap&amp;getlang={$smarty.get.getlang}&amp;action=edit&amp;edit={$smarty.get.edit}">{#text#|ucfirst}</a>
                        </li>
                        <li{if $smarty.get.tab eq "multimarkers"} class="active"{/if}>
                            <a href="/admin/plugins.php?name=gmap&amp;getlang={$smarty.get.getlang}&amp;action=edit&amp;edit={$smarty.get.edit}&amp;tab=multimarkers">Multi markers</a>
                        </li>
                    </ul>
                    <div class="mc-message clearfix"></div>
                    {if !$smarty.get.tab}
                        {include file="forms/edit.phtml"}
                    {elseif $smarty.get.tab eq "multimarkers"}
                        {include file="forms/rel-address.phtml"}
                    {/if}
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="js.phtml"}
</body>
</html>