{include file="common/head.phtml"}
<meta name="description" content="" />
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
{$refresh_plugins}
{literal}
<style type="text/css">
	#related_map{font-size:13px;color:black;}
.gmap3{}
</style>
{/literal}
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><img style="margin:0 5px 0 0;" class="lfloat" src="/{$pluginPath}/icon.png" alt="Gmap 3" width="16" height="16" />{$pluginName}</div>
					<div class="dashboard-content">
						<div class="column">
							<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
								<div class="dashboard-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open"><span style="float:left;" class="ui-icon ui-icon-circle-minus"></span>Modifier la carte</a></div>
								<div class="dashboard-widget-content">
								<div style="margin:5px;" class="button-link"><a href="{$pluginUrl}">Retour</a></div>
									<form id="forms-plugin-updateGmap" method="post" action="">
										<fieldset>
											<table class="table-tinymce">
												<tr>
													<td class="label"><label for="name_map" class="inlinelabel">Titre de la carte :</label></td>
												</tr>
												<tr>
													<td>
														<input type="hidden" id="idgmap" name="idgmap" value="{$smarty.get.editmap}" />
														<input type="text" id="name_map" name="name_map" class="inputtext ui-corner-all" value="{$name_map}" size="40" />
													</td>
												</tr>
												<tr>
													<td class="label"><label for="content_map" class="inlinelabel">Description :</label></td>
												</tr>
												<tr>
													<td>
														<textarea id="content_map" name="content_map" cols="50" rows="3" class="fulltext mceEditor ui-corner-all">{$content_map}</textarea>
													</td>
												</tr>
											</table>		
										</fieldset>
										<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
									</form>
								</div>
							</div>
						</div>
						<div class="column">
						<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
								<div class="dashboard-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open"><span style="float:left;" class="ui-icon ui-icon-circle-minus"></span>Ajouter une adresse relative</a></div>
								<div class="dashboard-widget-content">
									<form id="forms-plugin-gmap-add-rel-adress" method="post" action="">
										<fieldset>
										<table>
											<tr>
												<td class="label"><label for="society_ga" class="inlinelabel">Société :</label></td>
											</tr>
											<tr>
												<td>
													<input type="text" id="society_ga" name="society_ga" class="inputtext ui-corner-all" value="" size="20" />
												</td>
											</tr>
											<tr>
												<td class="label"><label for="country_ga" class="inlinelabel">Pays :</label></td>
											</tr>
											<tr>
												<td>
													<input type="text" id="country_ga" name="country_ga" class="inputtext ui-corner-all" value="" size="20" />
												</td>
											</tr>
											<tr>
												<td class="label"><label for="city_ga" class="inlinelabel">Ville :</label></td>
											</tr>
											<tr>
												<td>
													<input type="text" id="city_ga" name="city_ga" class="inputtext ui-corner-all" value="" size="20" />
												</td>
											</tr>
											<tr>
												<td class="label"><label for="adress_ga" class="inlinelabel">Adresse :</label></td>
											</tr>
											<tr>
												<td>
													<textarea id="adress_ga" name="adress_ga" cols="50" rows="3" class="fulltext ui-corner-all"></textarea>
												</td>
											</tr>
											<tr>
												<td>
												<div id="related_map"></div>
												<div>
													<input type="hidden" name="lat_ga" id="lat_ga" value="" />
													<input type="hidden" name="lng_ga" id="lng_ga" value="" />
												</div>
												</td>
											</tr>
										</table>			
									</fieldset>
									<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
									</form>
								</div>
							</div>
							<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
								<div class="dashboard-header ui-widget-header ui-corner-all">Les adresse relative</div>
								<div class="dashboard-widget-content">
									<div id="load_rel_gmap"></div>
								</div>
							</div>
							<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
								<div class="dashboard-header ui-widget-header ui-corner-all">Les cartes</div>
								<div class="dashboard-widget-content">
									<div id="load_plugin_gmap"></div>
								</div>
							</div>
						</div>
					</div>		
				</div>
{include file="cplugin/layout_down.phtml"}