{include file="section/head.phtml"}
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&language=fr" type="text/javascript"></script>
<title>Magix CMS | Admin</title>
</head>
<body class="plugins-contact">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="section/nav.phtml"}
                    <h1>Carte googlemap</h1>
                    <div class="row-fluid">
                        {foreach $array_lang as $key => $value nocache}
                            <div class="span3">
                                <div class="well">
                                    <h2><span class="icon-flag"></span> {$value|upper}</h2>
                                    <p>
                                        <a class="btn btn-primary" href="/{baseadmin}/plugins.php?name=gmap&amp;getlang={$key}&amp;action=list">
                                            <span class="icon-folder-open"></span> Administrer
                                        </a>
                                    </p>
                                </div>
                            </div>
                        {/foreach}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{*{include file="js.phtml"}*}
</body>
</html>