{script src="/min/?f=plugins/{$pluginName}/js/gmap3.min.js,plugins/{$pluginName}/js/admin.js" type="javascript"}
<script type="text/javascript">
{if $smarty.get.editmap}
var edit = "{$smarty.get.editmap}";
    {else}
var edit = '';
{/if}
$(function(){
if (typeof adminMap == "undefined") 
{
  console.log("adminMap is not defined");
}else{
    if(edit != ''){
        adminMap.runRelated(edit);
    }else{
        adminMap.runConfig();
    }
}
});
</script>