{include file="section/head.phtml"}
{include file="css.phtml"}
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&language=fr" type="text/javascript"></script>
<title>Magix CMS | Admin</title>
</head>
<body class="plugins-contact">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="section/nav.phtml"}
                    <h1>Carte googlemap</h1>
                    {include file="section/tab.phtml"}
                    <div class="mc-message clearfix"></div>
                    {if !$smarty.get.tab}
                        <p>
                            <a class="btn btn-primary" href="#" id="open-add">
                                <span class="icon-plus"></span> {#add_a_page#|ucfirst}
                            </a>
                        </p>
                        <div id="load_plugin_gmap"></div>
                    {elseif $smarty.get.tab eq "config"}
                        {include file="forms/config.phtml"}
                    {/if}
                </div>
            </div>
        </div>
    </div>
</div>
<div id="forms-add" class="hide" title="{#add_a_new_page#|ucfirst}">
    {include file="forms/add.phtml"}
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="js.phtml"}
</body>
</html>