<form id="forms_plugins_gmap_edit" method="post" action="">
    <p class="control-group">
        <label for="name_map">{#page_name#|ucfirst} :</label>
        <input type="text" class="input-xlarge" id="name_map" name="name_map" value="{$map.name_map}" size="50" />
    </p>
    <p>
        <label for="content_page" class="inlinelabel">{#label_content#|ucfirst} :</label>
        <textarea name="content_map" id="content_map" class="mceEditor">{$map.content_map}</textarea>
    </p>
    <p>
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>